Repository msusur/kodlama-pratikleri, pull requests merged in 2018-10, with the labels that each got.

#54 Tekrar eden harfleri bulmaca çözümünün Go implementasyonu
  cozumler/tekrar-eden-harfleri-bulmaca/golang/tekrar-eden-harfleri-bulma.go
Labels: golang, please review

#63 Add matrix question
  sorular/matrix_deki_maximum_kareyi_bulma.md
Labels: hacktoberfest, puzzle, reviewed

#61 Add new question.
  sorular/dizide-olmayan-sayiyi-bulma.md
Labels: hacktoberfest, puzzle, reviewed

#62 Add find missin number ruby solution.
  cozumler/dizide-olmayan-sayiyi-bulma/find_missin_number_test.rb
  cozumler/dizide-olmayan-sayiyi-bulma/find_missing_number.rb
Labels: hacktoberfest

#64 Closest Points & Sierpinski's Triangle Golang solution
  cozumler/en-yakin-noktalar/golang/closestpoints.go
  cozumler/sierpinski-ucgeni/golang/SierpinskisTriangle.png
  cozumler/sierpinski-ucgeni/golang/sierpinskitriangle.go
Labels: golang, please review

#69 En Yakın Noktalar Java Çözümü Eklendi
  cozumler/en-yakin-noktalar/java/EnYakinNoktalar.java
Labels: reviewed
